// Demo data for demonstration and testing purposes
import { RiskCategory, RiskStatus, RiskLevel, ControlType, ControlStatus, ControlCategory, AutomationLevel, ComplianceStatus } from '@prisma/client';
import { getRCSADemoData } from './demo-data-rcsa';

// Get comprehensive RCSA data
const rcsaData = getRCSADemoData('demo-org-id');

export const demoData = {
  // Demo Organization - Anonymized Financial Services Company
  organization: {
    id: 'demo-org-id',
    name: 'Demo Financial Corp',
    plan: 'enterprise',
    industry: 'Financial Services',
    size: 'Mid-Size Enterprise',
    location: 'United States',
    established: '2018-01-01',
    description: 'A regional financial services company providing banking, investment, and insurance products',
    employees: 850,
    branches: 15,
  },

  // Demo Risks - Comprehensive RCSA-Based Financial Services Risks (77 total)
  risks: rcsaData.risks || [
    {
      id: 'risk-1',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-001',
      title: 'Credit Risk - Default on Consumer Loans',
      description: 'Risk of financial loss due to borrower default on consumer loan portfolio, particularly in current economic environment with potential recession indicators',
      relatedRiskTaxonomy: 'Credit Risk - Consumer Lending',
      category: 'FINANCIAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 4,
      impact: 5,
      status: 'ASSESSED' as RiskStatus,
      riskScore: 20,
      riskLevel: 'HIGH' as RiskLevel,
      owner: 'Jennifer Chen',
      department: 'Credit Risk Management',
      businessUnit: 'Retail Banking',
      sourceOfRisk: 'Economic Downturn',
      riskType: 'External',
      question: 'Are credit assessment processes adequate to identify high-risk borrowers?',
      answerValue: 'Partially - Enhanced screening needed for current market conditions',
      comments: 'Portfolio showing increased delinquency rates in Q4 2024, require enhanced monitoring',
      identifiedDate: new Date('2024-01-15'),
      lastReviewDate: new Date('2024-12-01'),
      nextReviewDate: new Date('2025-03-01'),
      mitigationStrategy: 'Implement enhanced credit scoring models, increase loan loss provisions, tighten underwriting criteria',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-1'],
      tags: ['credit-risk', 'consumer-loans', 'default-risk'],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'risk-2',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-002',
      title: 'Anti-Money Laundering - Suspicious Transaction Detection',
      description: 'Risk of regulatory penalties and reputational damage due to inadequate detection of money laundering activities through customer accounts',
      relatedRiskTaxonomy: 'Compliance Risk - AML/CTF',
      category: 'COMPLIANCE' as RiskCategory,
      severity: 'CRITICAL',
      likelihood: 3,
      impact: 5,
      status: 'IDENTIFIED' as RiskStatus,
      riskScore: 15,
      riskLevel: 'HIGH' as RiskLevel,
      owner: 'Marcus Rodriguez',
      department: 'Compliance - AML',
      businessUnit: 'Risk & Compliance',
      sourceOfRisk: 'Regulatory Requirements',
      riskType: 'Regulatory',
      question: 'Are AML monitoring systems effectively detecting suspicious transaction patterns?',
      answerValue: 'Yes - but requires enhancement for emerging digital payment methods',
      comments: 'Recent regulatory guidance requires enhanced monitoring for cryptocurrency transactions',
      identifiedDate: new Date('2024-02-01'),
      lastReviewDate: new Date('2024-11-15'),
      nextReviewDate: new Date('2025-02-15'),
      mitigationStrategy: 'Upgrade transaction monitoring systems, enhance staff training, implement advanced analytics',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-2'],
      tags: ['aml', 'compliance', 'transaction-monitoring'],
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-11-15'),
    },
    {
      id: 'risk-3',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-003',
      title: 'Interest Rate Risk - Asset-Liability Mismatch',
      description: 'Risk of reduced net interest margin due to rising interest rates affecting variable rate liabilities faster than fixed rate assets',
      relatedRiskTaxonomy: 'Market Risk - Interest Rate Risk',
      category: 'FINANCIAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 4,
      impact: 4,
      status: 'ASSESSED' as RiskStatus,
      riskScore: 16,
      riskLevel: 'HIGH' as RiskLevel,
      owner: 'Sarah Kim',
      department: 'Asset Liability Management',
      businessUnit: 'Treasury',
      sourceOfRisk: 'Market Volatility',
      riskType: 'Market',
      question: 'Is the duration gap between assets and liabilities within acceptable limits?',
      answerValue: 'No - Duration gap has widened beyond risk appetite',
      comments: 'Fed rate increases have created significant ALM pressure, need hedge strategies',
      identifiedDate: new Date('2024-03-10'),
      lastReviewDate: new Date('2024-12-10'),
      nextReviewDate: new Date('2025-03-10'),
      mitigationStrategy: 'Implement interest rate hedging strategies, adjust loan pricing models, duration matching',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-3'],
      tags: ['interest-rate-risk', 'alm', 'market-risk'],
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-12-10'),
    },
    {
      id: 'risk-4',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-004',
      title: 'Operational Resilience - Core Banking System Failure',
      description: 'Risk of business disruption due to core banking system outage affecting customer transactions and regulatory reporting',
      relatedRiskTaxonomy: 'Operational Risk - System Availability',
      category: 'OPERATIONAL' as RiskCategory,
      severity: 'CRITICAL',
      likelihood: 2,
      impact: 5,
      status: 'MITIGATED' as RiskStatus,
      riskScore: 10,
      riskLevel: 'MEDIUM' as RiskLevel,
      owner: 'David Park',
      department: 'IT Operations',
      businessUnit: 'Technology',
      sourceOfRisk: 'System Failure',
      riskType: 'Internal',
      question: 'Are backup and recovery procedures for core banking systems adequate?',
      answerValue: 'Yes - but disaster recovery testing needs improvement',
      comments: 'Recent system upgrade completed, enhanced monitoring implemented',
      identifiedDate: new Date('2024-01-20'),
      lastReviewDate: new Date('2024-10-20'),
      nextReviewDate: new Date('2025-01-20'),
      mitigationStrategy: 'Implement redundant systems, enhance disaster recovery procedures, regular failover testing',
      residualRisk: 'LOW',
      controls: ['ctrl-4'],
      tags: ['operational-resilience', 'system-failure', 'business-continuity'],
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-10-20'),
    },
    {
      id: 'risk-5',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-005',
      title: 'Third Party Risk - Payment Processor Vendor',
      description: 'Risk of service disruption and regulatory compliance issues due to critical payment processor vendor security breach or operational failure',
      relatedRiskTaxonomy: 'Third Party Risk - Critical Vendors',
      category: 'OPERATIONAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 3,
      impact: 4,
      status: 'IDENTIFIED' as RiskStatus,
      riskScore: 12,
      riskLevel: 'MEDIUM' as RiskLevel,
      owner: 'Lisa Wang',
      department: 'Vendor Risk Management',
      businessUnit: 'Operations',
      sourceOfRisk: 'Third Party Dependencies',
      riskType: 'External',
      question: 'Are critical vendor risk assessments current and comprehensive?',
      answerValue: 'Partially - Require enhanced cybersecurity assessment',
      comments: 'Annual vendor review scheduled for Q1 2025, focusing on operational resilience',
      identifiedDate: new Date('2024-04-05'),
      lastReviewDate: new Date('2024-11-05'),
      nextReviewDate: new Date('2025-05-05'),
      mitigationStrategy: 'Enhanced vendor due diligence, alternative vendor identification, contingency planning',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-5'],
      tags: ['third-party-risk', 'vendor-management', 'payment-processor'],
      createdAt: new Date('2024-04-05'),
      updatedAt: new Date('2024-11-05'),
    },
    {
      id: 'risk-6',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-006',
      title: 'Regulatory Compliance - Basel III Capital Requirements',
      description: 'Risk of regulatory sanctions due to non-compliance with Basel III capital adequacy and liquidity coverage ratio requirements',
      relatedRiskTaxonomy: 'Regulatory Risk - Capital Management',
      category: 'COMPLIANCE' as RiskCategory,
      severity: 'CRITICAL',
      likelihood: 2,
      impact: 5,
      status: 'ASSESSED' as RiskStatus,
      riskScore: 10,
      riskLevel: 'MEDIUM' as RiskLevel,
      owner: 'Thomas Anderson',
      department: 'Regulatory Reporting',
      businessUnit: 'Risk & Compliance',
      sourceOfRisk: 'Regulatory Changes',
      riskType: 'Regulatory',
      question: 'Are capital ratios consistently maintained above regulatory minimums?',
      answerValue: 'Yes - maintaining adequate buffer above minimum requirements',
      comments: 'Capital planning process enhanced to accommodate new regulatory requirements',
      identifiedDate: new Date('2024-05-12'),
      lastReviewDate: new Date('2024-12-05'),
      nextReviewDate: new Date('2025-06-05'),
      mitigationStrategy: 'Capital planning optimization, stress testing enhancement, regulatory monitoring',
      residualRisk: 'LOW',
      controls: ['ctrl-6'],
      tags: ['basel-iii', 'capital-adequacy', 'regulatory-compliance'],
      createdAt: new Date('2024-05-12'),
      updatedAt: new Date('2024-12-05'),
    },
    {
      id: 'risk-7',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-007',
      title: 'Market Volatility - Trading Portfolio Risk',
      description: 'Risk of significant losses in trading portfolio due to adverse market movements and volatility in equity and bond markets',
      relatedRiskTaxonomy: 'Market Risk - Trading Risk',
      category: 'FINANCIAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 4,
      impact: 4,
      status: 'IDENTIFIED' as RiskStatus,
      riskScore: 16,
      riskLevel: 'HIGH' as RiskLevel,
      owner: 'Rachel Green',
      department: 'Trading Risk Management',
      businessUnit: 'Investment Banking',
      sourceOfRisk: 'Market Volatility',
      riskType: 'Market',
      question: 'Are value-at-risk limits being monitored and adhered to daily?',
      answerValue: 'Yes - but limits may need adjustment for current market conditions',
      comments: 'Increased volatility in Q4 2024 requires enhanced position monitoring',
      identifiedDate: new Date('2024-06-18'),
      lastReviewDate: new Date('2024-12-15'),
      nextReviewDate: new Date('2025-03-15'),
      mitigationStrategy: 'Enhanced VaR monitoring, position limit adjustments, diversification strategies',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-7'],
      tags: ['market-risk', 'trading', 'volatility'],
      createdAt: new Date('2024-06-18'),
      updatedAt: new Date('2024-12-15'),
    },
    {
      id: 'risk-8',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-008',
      title: 'Business Continuity - Pandemic Response',
      description: 'Risk of operational disruption due to widespread staff unavailability during pandemic or similar public health emergency',
      relatedRiskTaxonomy: 'Business Continuity - Health Emergency',
      category: 'OPERATIONAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 3,
      impact: 4,
      status: 'MITIGATED' as RiskStatus,
      riskScore: 12,
      riskLevel: 'MEDIUM' as RiskLevel,
      owner: 'Michael Torres',
      department: 'Business Continuity',
      businessUnit: 'Operations',
      sourceOfRisk: 'External Events',
      riskType: 'External',
      question: 'Are remote work capabilities sufficient for maintaining critical operations?',
      answerValue: 'Yes - enhanced capabilities implemented post-COVID',
      comments: 'Pandemic response plan updated based on COVID-19 lessons learned',
      identifiedDate: new Date('2024-07-08'),
      lastReviewDate: new Date('2024-11-25'),
      nextReviewDate: new Date('2025-07-25'),
      mitigationStrategy: 'Remote work infrastructure, cross-training programs, alternative site operations',
      residualRisk: 'LOW',
      controls: ['ctrl-8'],
      tags: ['business-continuity', 'pandemic', 'remote-work'],
      createdAt: new Date('2024-07-08'),
      updatedAt: new Date('2024-11-25'),
    },
    {
      id: 'risk-9',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-009',
      title: 'Fraud Prevention - Digital Channel Security',
      description: 'Risk of financial losses and reputational damage due to fraudulent activities through digital banking channels including mobile and online platforms',
      relatedRiskTaxonomy: 'Fraud Risk - Digital Channels',
      category: 'OPERATIONAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 4,
      impact: 4,
      status: 'ASSESSED' as RiskStatus,
      riskScore: 16,
      riskLevel: 'HIGH' as RiskLevel,
      owner: 'Amanda Johnson',
      department: 'Digital Security',
      businessUnit: 'Digital Banking',
      sourceOfRisk: 'Cyber Threats',
      riskType: 'External',
      question: 'Are fraud detection systems adequate for current digital transaction volumes?',
      answerValue: 'Partially - require enhancement for real-time detection',
      comments: 'Increased sophisticated fraud attempts targeting mobile banking platform',
      identifiedDate: new Date('2024-08-22'),
      lastReviewDate: new Date('2024-12-18'),
      nextReviewDate: new Date('2025-02-18'),
      mitigationStrategy: 'Advanced fraud analytics, multi-factor authentication, behavioral monitoring',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-9'],
      tags: ['fraud-prevention', 'digital-banking', 'cybersecurity'],
      createdAt: new Date('2024-08-22'),
      updatedAt: new Date('2024-12-18'),
    },
    {
      id: 'risk-10',
      organizationId: 'demo-org-id',
      itemNumber: 'RCSA-010',
      title: 'Liquidity Management - Deposit Concentration Risk',
      description: 'Risk of liquidity shortage due to high concentration of deposits from few large institutional clients and potential simultaneous withdrawal',
      relatedRiskTaxonomy: 'Liquidity Risk - Funding Concentration',
      category: 'FINANCIAL' as RiskCategory,
      severity: 'HIGH',
      likelihood: 3,
      impact: 5,
      status: 'IDENTIFIED' as RiskStatus,
      riskScore: 15,
      riskLevel: 'HIGH' as RiskLevel,
      owner: 'Kevin Liu',
      department: 'Liquidity Management',
      businessUnit: 'Treasury',
      sourceOfRisk: 'Funding Concentration',
      riskType: 'Internal',
      question: 'Is deposit base adequately diversified to avoid concentration risk?',
      answerValue: 'No - top 10 depositors represent 40% of total deposits',
      comments: 'Deposit diversification strategy needs acceleration, particularly retail segment',
      identifiedDate: new Date('2024-09-30'),
      lastReviewDate: new Date('2024-12-20'),
      nextReviewDate: new Date('2025-03-30'),
      mitigationStrategy: 'Deposit diversification campaign, contingency funding arrangements, liquidity buffer enhancement',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-10'],
      tags: ['liquidity-risk', 'deposit-concentration', 'funding'],
      createdAt: new Date('2024-09-30'),
      updatedAt: new Date('2024-12-20'),
    },
  ],

  // Demo Controls - Corresponding Financial Services Controls for RCSA Risks (77 total)
  controls: rcsaData.controls || [
    {
      id: 'ctrl-1',
      organizationId: 'demo-org-id',
      name: 'Enhanced Credit Underwriting and Portfolio Monitoring',
      description: 'Comprehensive credit assessment process with enhanced underwriting criteria, real-time portfolio monitoring, and early warning indicators for potential defaults',
      type: 'PREVENTIVE' as ControlType,
      category: 'ADMINISTRATIVE' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 85,
      owner: 'Jennifer Chen',
      implementationDate: new Date('2024-02-01'),
      lastTestDate: new Date('2024-12-01'),
      nextTestDate: new Date('2025-03-01'),
      testFrequency: 'MONTHLY',
      automationLevel: 'SEMI_AUTOMATED' as AutomationLevel,
      cost: 180000,
      relatedRisks: ['risk-1'],
      evidence: ['Credit policy documentation', 'Portfolio monitoring reports', 'Default rate statistics'],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'ctrl-2',
      organizationId: 'demo-org-id',
      name: 'Advanced AML Transaction Monitoring System',
      description: 'Real-time transaction monitoring system with AI-enhanced pattern recognition for suspicious activity detection and automated regulatory reporting',
      type: 'DETECTIVE' as ControlType,
      category: 'TECHNICAL' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 92,
      owner: 'Marcus Rodriguez',
      implementationDate: new Date('2024-01-20'),
      lastTestDate: new Date('2024-11-15'),
      nextTestDate: new Date('2025-02-15'),
      testFrequency: 'WEEKLY',
      automationLevel: 'FULLY_AUTOMATED' as AutomationLevel,
      cost: 250000,
      relatedRisks: ['risk-2'],
      evidence: ['AML monitoring system reports', 'Suspicious activity reports', 'Regulatory compliance certificates'],
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-11-15'),
    },
    {
      id: 'ctrl-3',
      organizationId: 'demo-org-id',
      name: 'Asset-Liability Management and Interest Rate Hedging',
      description: 'Comprehensive ALM framework with duration matching strategies, interest rate hedging instruments, and regular stress testing for rate sensitivity',
      type: 'PREVENTIVE' as ControlType,
      category: 'MANAGEMENT' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 88,
      owner: 'Sarah Kim',
      implementationDate: new Date('2024-03-01'),
      lastTestDate: new Date('2024-12-05'),
      nextTestDate: new Date('2025-03-05'),
      testFrequency: 'MONTHLY',
      automationLevel: 'SEMI_AUTOMATED' as AutomationLevel,
      cost: 320000,
      relatedRisks: ['risk-3'],
      evidence: ['ALM reports', 'Hedge effectiveness testing', 'Interest rate risk metrics'],
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-12-05'),
    },
    {
      id: 'ctrl-4',
      organizationId: 'demo-org-id',
      name: 'Core Banking System Redundancy and Recovery',
      description: 'High-availability core banking architecture with real-time replication, automated failover capabilities, and comprehensive disaster recovery procedures',
      type: 'CORRECTIVE' as ControlType,
      category: 'TECHNICAL' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 95,
      owner: 'David Park',
      implementationDate: new Date('2024-01-01'),
      lastTestDate: new Date('2024-10-01'),
      nextTestDate: new Date('2025-01-01'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'FULLY_AUTOMATED' as AutomationLevel,
      cost: 450000,
      relatedRisks: ['risk-4'],
      evidence: ['System availability reports', 'DR test results', 'RTO/RPO metrics'],
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-10-01'),
    },
    {
      id: 'ctrl-5',
      organizationId: 'demo-org-id',
      name: 'Comprehensive Third-Party Vendor Risk Management',
      description: 'End-to-end vendor risk management program including due diligence, ongoing monitoring, performance assessment, and contingency planning for critical vendors',
      type: 'PREVENTIVE' as ControlType,
      category: 'ADMINISTRATIVE' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 82,
      owner: 'Lisa Wang',
      implementationDate: new Date('2024-02-15'),
      lastTestDate: new Date('2024-11-01'),
      nextTestDate: new Date('2025-05-01'),
      testFrequency: 'SEMI_ANNUALLY',
      automationLevel: 'SEMI_AUTOMATED' as AutomationLevel,
      cost: 120000,
      relatedRisks: ['risk-5'],
      evidence: ['Vendor risk assessments', 'Performance scorecards', 'Contingency plans'],
      createdAt: new Date('2024-04-05'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'ctrl-6',
      organizationId: 'demo-org-id',
      name: 'Automated Regulatory Capital and Liquidity Monitoring',
      description: 'Real-time monitoring and reporting system for Basel III capital ratios, liquidity coverage ratios, and regulatory compliance with automated alert mechanisms',
      type: 'DETECTIVE' as ControlType,
      category: 'TECHNICAL' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 96,
      owner: 'Thomas Anderson',
      implementationDate: new Date('2024-04-01'),
      lastTestDate: new Date('2024-12-01'),
      nextTestDate: new Date('2025-03-01'),
      testFrequency: 'MONTHLY',
      automationLevel: 'FULLY_AUTOMATED' as AutomationLevel,
      cost: 200000,
      relatedRisks: ['risk-6'],
      evidence: ['Capital adequacy reports', 'Liquidity monitoring dashboards', 'Regulatory submission records'],
      createdAt: new Date('2024-05-12'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'ctrl-7',
      organizationId: 'demo-org-id',
      name: 'Trading Risk Limits and Value-at-Risk Management',
      description: 'Comprehensive market risk management framework with daily VaR calculations, position limits, stress testing, and real-time risk monitoring for trading portfolios',
      type: 'PREVENTIVE' as ControlType,
      category: 'MANAGEMENT' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 90,
      owner: 'Rachel Green',
      implementationDate: new Date('2024-03-15'),
      lastTestDate: new Date('2024-12-15'),
      nextTestDate: new Date('2025-03-15'),
      testFrequency: 'DAILY',
      automationLevel: 'FULLY_AUTOMATED' as AutomationLevel,
      cost: 300000,
      relatedRisks: ['risk-7'],
      evidence: ['VaR reports', 'Position limit monitoring', 'Stress test results'],
      createdAt: new Date('2024-06-18'),
      updatedAt: new Date('2024-12-15'),
    },
    {
      id: 'ctrl-8',
      organizationId: 'demo-org-id',
      name: 'Business Continuity and Remote Operations Framework',
      description: 'Comprehensive business continuity plan with remote work capabilities, alternative site operations, cross-training programs, and pandemic response procedures',
      type: 'CORRECTIVE' as ControlType,
      category: 'OPERATIONAL' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 87,
      owner: 'Michael Torres',
      implementationDate: new Date('2024-05-01'),
      lastTestDate: new Date('2024-11-25'),
      nextTestDate: new Date('2025-05-25'),
      testFrequency: 'SEMI_ANNUALLY',
      automationLevel: 'SEMI_AUTOMATED' as AutomationLevel,
      cost: 180000,
      relatedRisks: ['risk-8'],
      evidence: ['BCP test results', 'Remote work assessments', 'Staff cross-training records'],
      createdAt: new Date('2024-07-08'),
      updatedAt: new Date('2024-11-25'),
    },
    {
      id: 'ctrl-9',
      organizationId: 'demo-org-id',
      name: 'Advanced Digital Fraud Detection and Prevention',
      description: 'Multi-layered fraud prevention system with AI-powered behavioral analytics, real-time transaction scoring, and adaptive authentication for digital channels',
      type: 'DETECTIVE' as ControlType,
      category: 'TECHNICAL' as ControlCategory,
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 91,
      owner: 'Amanda Johnson',
      implementationDate: new Date('2024-01-10'),
      lastTestDate: new Date('2024-12-18'),
      nextTestDate: new Date('2025-02-18'),
      testFrequency: 'WEEKLY',
      automationLevel: 'FULLY_AUTOMATED' as AutomationLevel,
      cost: 275000,
      relatedRisks: ['risk-9'],
      evidence: ['Fraud detection reports', 'False positive analysis', 'Authentication metrics'],
      createdAt: new Date('2024-08-22'),
      updatedAt: new Date('2024-12-18'),
    },
    {
      id: 'ctrl-10',
      organizationId: 'demo-org-id',
      name: 'Deposit Diversification and Liquidity Buffer Management',
      description: 'Strategic deposit diversification program with retail customer acquisition, liquidity stress testing, and contingency funding arrangements to reduce concentration risk',
      type: 'PREVENTIVE' as ControlType,
      category: 'MANAGEMENT' as ControlCategory,
      status: 'TESTING' as ControlStatus,
      effectiveness: 75,
      owner: 'Kevin Liu',
      implementationDate: new Date('2024-02-20'),
      lastTestDate: new Date('2024-12-20'),
      nextTestDate: new Date('2025-03-20'),
      testFrequency: 'MONTHLY',
      automationLevel: 'SEMI_AUTOMATED' as AutomationLevel,
      cost: 150000,
      relatedRisks: ['risk-10'],
      evidence: ['Deposit concentration analysis', 'Liquidity stress test results', 'Funding diversification reports'],
      createdAt: new Date('2024-09-30'),
      updatedAt: new Date('2024-12-20'),
    },
  ],

  // Demo Vendor Assessments
  vendorAssessments: [
    {
      id: 'vendor-1',
      organizationId: 'demo-org-id',
      vendorName: 'CloudTech Solutions',
      vendorType: 'Cloud Infrastructure Provider',
      criticality: 'CRITICAL',
      assessmentDate: new Date('2024-11-01'),
      nextAssessmentDate: new Date('2025-05-01'),
      overallRiskScore: 25,
      securityScore: 90,
      complianceScore: 88,
      financialScore: 92,
      operationalScore: 85,
      status: 'APPROVED',
      findings: [
        'Strong security controls in place',
        'SOC 2 Type II certified',
        'Minor improvement needed in incident response procedures',
      ],
      recommendations: [
        'Review incident response SLA',
        'Request quarterly security reports',
      ],
      contractValue: 500000,
      contractExpiry: new Date('2025-12-31'),
      primaryContact: 'vendor.contact@cloudtech.com',
      certifications: ['SOC 2', 'ISO 27001', 'PCI DSS'],
      createdAt: new Date('2024-11-01'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'vendor-2',
      organizationId: 'demo-org-id',
      vendorName: 'SecurePayments Inc',
      vendorType: 'Payment Processor',
      criticality: 'CRITICAL',
      assessmentDate: new Date('2024-10-15'),
      nextAssessmentDate: new Date('2025-04-15'),
      overallRiskScore: 30,
      securityScore: 85,
      complianceScore: 95,
      financialScore: 88,
      operationalScore: 82,
      status: 'APPROVED',
      findings: [
        'PCI DSS Level 1 compliant',
        'Robust fraud detection mechanisms',
        'Need for enhanced API security documentation',
      ],
      recommendations: [
        'Implement API rate limiting',
        'Enhance monitoring of transaction anomalies',
      ],
      contractValue: 250000,
      contractExpiry: new Date('2025-10-31'),
      primaryContact: 'security@securepayments.com',
      certifications: ['PCI DSS Level 1', 'SOC 1', 'ISO 27001'],
      createdAt: new Date('2024-10-15'),
      updatedAt: new Date('2024-10-15'),
    },
    {
      id: 'vendor-3',
      organizationId: 'demo-org-id',
      vendorName: 'DataAnalytics Pro',
      vendorType: 'Analytics Platform',
      criticality: 'HIGH',
      assessmentDate: new Date('2024-09-20'),
      nextAssessmentDate: new Date('2025-03-20'),
      overallRiskScore: 40,
      securityScore: 78,
      complianceScore: 82,
      financialScore: 90,
      operationalScore: 88,
      status: 'CONDITIONAL',
      findings: [
        'Data encryption needs improvement',
        'Access controls are adequate',
        'Missing GDPR compliance documentation',
      ],
      recommendations: [
        'Implement end-to-end encryption',
        'Complete GDPR compliance audit',
        'Enhance user access logging',
      ],
      contractValue: 150000,
      contractExpiry: new Date('2025-09-30'),
      primaryContact: 'support@dataanalytics.com',
      certifications: ['SOC 2 Type I'],
      createdAt: new Date('2024-09-20'),
      updatedAt: new Date('2024-09-20'),
    },
    {
      id: 'vendor-4',
      organizationId: 'demo-org-id',
      vendorName: 'HR Management Systems',
      vendorType: 'HR Software',
      criticality: 'MEDIUM',
      assessmentDate: new Date('2024-08-10'),
      nextAssessmentDate: new Date('2025-08-10'),
      overallRiskScore: 35,
      securityScore: 80,
      complianceScore: 85,
      financialScore: 82,
      operationalScore: 79,
      status: 'APPROVED',
      findings: [
        'Good data protection practices',
        'Regular security updates',
        'Need for better disaster recovery documentation',
      ],
      recommendations: [
        'Document DR procedures',
        'Implement MFA for all admin accounts',
      ],
      contractValue: 75000,
      contractExpiry: new Date('2025-08-31'),
      primaryContact: 'security@hrsystems.com',
      certifications: ['ISO 27001', 'GDPR Compliant'],
      createdAt: new Date('2024-08-10'),
      updatedAt: new Date('2024-08-10'),
    },
    {
      id: 'vendor-5',
      organizationId: 'demo-org-id',
      vendorName: 'Marketing Automation Co',
      vendorType: 'Marketing Software',
      criticality: 'LOW',
      assessmentDate: new Date('2024-07-05'),
      nextAssessmentDate: new Date('2025-07-05'),
      overallRiskScore: 45,
      securityScore: 75,
      complianceScore: 78,
      financialScore: 85,
      operationalScore: 80,
      status: 'UNDER_REVIEW',
      findings: [
        'Basic security controls in place',
        'Limited compliance certifications',
        'Adequate data handling procedures',
      ],
      recommendations: [
        'Obtain SOC 2 certification',
        'Enhance API security',
        'Implement data retention policies',
      ],
      contractValue: 50000,
      contractExpiry: new Date('2025-07-31'),
      primaryContact: 'info@marketingauto.com',
      certifications: ['GDPR Compliant'],
      createdAt: new Date('2024-07-05'),
      updatedAt: new Date('2024-07-05'),
    },
  ],

  // Demo Compliance Items
  compliance: [
    {
      id: 'comp-1',
      organizationId: 'demo-org-id',
      framework: 'GDPR',
      requirement: 'Data Protection Officer Appointment',
      description: 'Appoint a Data Protection Officer to oversee GDPR compliance',
      status: 'COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-01-01'),
      lastAssessmentDate: new Date('2024-11-01'),
      evidence: ['DPO appointment letter', 'DPO responsibilities document'],
      responsibleParty: 'Legal Department',
      notes: 'DPO appointed and actively monitoring compliance',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'comp-2',
      organizationId: 'demo-org-id',
      framework: 'SOC 2',
      requirement: 'Access Control Review',
      description: 'Quarterly review of user access rights and privileges',
      status: 'COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-03-31'),
      lastAssessmentDate: new Date('2024-12-01'),
      evidence: ['Access review reports', 'Approval documentation'],
      responsibleParty: 'IT Security',
      notes: 'Q4 2024 review completed successfully',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'comp-3',
      organizationId: 'demo-org-id',
      framework: 'PCI DSS',
      requirement: 'Network Segmentation',
      description: 'Maintain network segmentation between cardholder data environment and other networks',
      status: 'PARTIALLY_COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-02-28'),
      lastAssessmentDate: new Date('2024-10-15'),
      evidence: ['Network diagram', 'Segmentation test results'],
      responsibleParty: 'Network Team',
      notes: 'Additional segmentation required for new payment processing system',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-10-15'),
    },
    {
      id: 'comp-4',
      organizationId: 'demo-org-id',
      framework: 'ISO 27001',
      requirement: 'Risk Assessment',
      description: 'Annual information security risk assessment',
      status: 'COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-06-30'),
      lastAssessmentDate: new Date('2024-06-30'),
      evidence: ['Risk assessment report', 'Risk treatment plan'],
      responsibleParty: 'Risk Management',
      notes: '2024 assessment completed with all high risks addressed',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-06-30'),
    },
    {
      id: 'comp-5',
      organizationId: 'demo-org-id',
      framework: 'HIPAA',
      requirement: 'Business Associate Agreements',
      description: 'Maintain current BAAs with all vendors handling PHI',
      status: 'NON_COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-01-31'),
      lastAssessmentDate: new Date('2024-11-15'),
      evidence: ['BAA inventory', 'Signed agreements'],
      responsibleParty: 'Legal Department',
      notes: '3 vendor BAAs pending renewal',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-11-15'),
    },
  ],

  // Demo Test Results
  testResults: [
    {
      id: 'test-1',
      controlId: 'ctrl-1',
      testDate: new Date('2024-12-01'),
      testType: 'Automated',
      result: 'PASS',
      findings: 'MFA enforcement working correctly across all systems',
      evidence: ['Test execution logs', 'Screenshot evidence'],
      tester: 'Security Team',
      nextTestDate: new Date('2025-01-01'),
    },
    {
      id: 'test-2',
      controlId: 'ctrl-2',
      testDate: new Date('2024-11-15'),
      testType: 'Manual',
      result: 'PASS',
      findings: 'All sensitive data properly encrypted',
      evidence: ['Encryption scan results', 'Configuration review'],
      tester: 'Security Team',
      nextTestDate: new Date('2025-02-15'),
    },
    {
      id: 'test-3',
      controlId: 'ctrl-7',
      testDate: new Date('2024-09-15'),
      testType: 'Manual',
      result: 'FAIL',
      findings: '2 vendors missing security documentation',
      evidence: ['Assessment checklist', 'Vendor communication'],
      tester: 'Procurement Team',
      nextTestDate: new Date('2025-03-15'),
    },
  ],

  // Demo Incidents
  incidents: [
    {
      id: 'inc-1',
      organizationId: 'demo-org-id',
      title: 'Phishing Email Campaign Detected',
      description: 'Multiple employees received sophisticated phishing emails',
      severity: 'MEDIUM',
      status: 'RESOLVED',
      detectedDate: new Date('2024-11-20'),
      resolvedDate: new Date('2024-11-21'),
      impactedSystems: ['Email System', 'User Accounts'],
      rootCause: 'Social engineering attack',
      remediation: 'User training conducted, email filters updated',
      lessonsLearned: 'Need for enhanced email security and regular phishing simulations',
      createdAt: new Date('2024-11-20'),
      updatedAt: new Date('2024-11-21'),
    },
    {
      id: 'inc-2',
      organizationId: 'demo-org-id',
      title: 'Database Performance Degradation',
      description: 'Production database experiencing slow query performance',
      severity: 'HIGH',
      status: 'IN_PROGRESS',
      detectedDate: new Date('2024-12-10'),
      resolvedDate: null,
      impactedSystems: ['Production Database', 'Web Application'],
      rootCause: 'Under investigation',
      remediation: 'Query optimization in progress',
      lessonsLearned: '',
      createdAt: new Date('2024-12-10'),
      updatedAt: new Date('2024-12-10'),
    },
  ],

  // Demo Audit Logs
  auditLogs: [
    {
      id: 'audit-1',
      timestamp: new Date('2024-12-12T10:30:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'LOGIN',
      resource: 'Authentication System',
      details: 'Successful login from IP 192.168.1.100',
      result: 'SUCCESS',
    },
    {
      id: 'audit-2',
      timestamp: new Date('2024-12-12T10:35:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'VIEW',
      resource: 'Risk Dashboard',
      details: 'Accessed risk dashboard',
      result: 'SUCCESS',
    },
    {
      id: 'audit-3',
      timestamp: new Date('2024-12-12T10:40:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'UPDATE',
      resource: 'Risk Assessment',
      details: 'Updated risk score for Risk ID: risk-1',
      result: 'SUCCESS',
    },
    {
      id: 'audit-4',
      timestamp: new Date('2024-12-12T10:45:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'CREATE',
      resource: 'Control Test',
      details: 'Initiated control test for Control ID: ctrl-1',
      result: 'SUCCESS',
    },
  ],

  // Demo Dashboard Metrics - Updated for RCSA-based data
  metrics: {
    ...rcsaData.metrics,
    vendorsAssessed: 5,
    vendorsApproved: 3,
    openIncidents: 2,
    resolvedIncidents: 8,
    upcomingAssessments: 5,
    overdueItems: 1,
  },
};

// Helper function to get demo data for a specific entity
export function getDemoData(entity: string, organizationId: string) {
  // Use production-safe demo mode check
  if (!shouldServeDemoData(undefined, organizationId)) {
    return null;
  }

  switch (entity) {
    case 'risks':
      return demoData.risks;
    case 'controls':
      return demoData.controls;
    case 'vendors':
      return demoData.vendorAssessments;
    case 'compliance':
      return demoData.compliance;
    case 'tests':
      return demoData.testResults;
    case 'incidents':
      return demoData.incidents;
    case 'audit':
      return demoData.auditLogs;
    case 'metrics':
      return demoData.metrics;
    case 'organization':
      return demoData.organization;
    default:
      return null;
  }
}

// Import production-safe demo mode controls
import { shouldServeDemoData } from './demo/demo-mode';

// Helper to check if a user is using demo mode
export function isDemoUser(userId: string): boolean {
  return shouldServeDemoData(userId, undefined);
}

// Helper to get demo user details
export function getDemoUser() {
  return {
    id: 'demo-admin-id',
    email: 'admin@riscura.com',
    firstName: 'Demo',
    lastName: 'Admin',
    role: 'ADMIN',
    permissions: ['*'],
    organizationId: 'demo-org-id',
    organization: demoData.organization,
  };
}