// Demo data for demonstration and testing purposes
import { RiskSeverity, RiskStatus, ControlType, ControlStatus, ComplianceStatus } from '@/types';

export const demoData = {
  // Demo Organization
  organization: {
    id: 'demo-org-id',
    name: 'Demo Organization',
    plan: 'enterprise',
    industry: 'Financial Services',
    size: 'Large Enterprise',
    location: 'United States',
    established: '2020-01-01',
  },

  // Demo Risks
  risks: [
    {
      id: 'risk-1',
      organizationId: 'demo-org-id',
      title: 'Data Breach Risk',
      description: 'Risk of unauthorized access to sensitive customer data through cyber attacks or insider threats',
      category: 'Cybersecurity',
      severity: 'HIGH' as RiskSeverity,
      likelihood: 'MEDIUM',
      impact: 'HIGH',
      status: 'ACTIVE' as RiskStatus,
      riskScore: 85,
      owner: 'John Smith',
      department: 'IT Security',
      identifiedDate: new Date('2024-01-15'),
      lastReviewDate: new Date('2024-12-01'),
      nextReviewDate: new Date('2025-03-01'),
      mitigationStrategy: 'Implement multi-factor authentication, encryption at rest and in transit, regular security audits',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-1', 'ctrl-2', 'ctrl-3'],
      tags: ['cybersecurity', 'data-protection', 'critical'],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'risk-2',
      organizationId: 'demo-org-id',
      title: 'Regulatory Compliance Risk',
      description: 'Risk of non-compliance with GDPR, CCPA, and other data protection regulations',
      category: 'Compliance',
      severity: 'HIGH' as RiskSeverity,
      likelihood: 'LOW',
      impact: 'VERY_HIGH',
      status: 'ACTIVE' as RiskStatus,
      riskScore: 75,
      owner: 'Sarah Johnson',
      department: 'Legal & Compliance',
      identifiedDate: new Date('2024-02-01'),
      lastReviewDate: new Date('2024-11-15'),
      nextReviewDate: new Date('2025-02-15'),
      mitigationStrategy: 'Regular compliance audits, automated compliance monitoring, staff training programs',
      residualRisk: 'LOW',
      controls: ['ctrl-4', 'ctrl-5', 'ctrl-6'],
      tags: ['compliance', 'regulatory', 'gdpr', 'ccpa'],
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-11-15'),
    },
    {
      id: 'risk-3',
      organizationId: 'demo-org-id',
      title: 'Supply Chain Disruption',
      description: 'Risk of business disruption due to third-party vendor failures or supply chain attacks',
      category: 'Operational',
      severity: 'MEDIUM' as RiskSeverity,
      likelihood: 'MEDIUM',
      impact: 'MEDIUM',
      status: 'UNDER_REVIEW' as RiskStatus,
      riskScore: 60,
      owner: 'Michael Chen',
      department: 'Operations',
      identifiedDate: new Date('2024-03-10'),
      lastReviewDate: new Date('2024-12-10'),
      nextReviewDate: new Date('2025-03-10'),
      mitigationStrategy: 'Vendor risk assessments, backup suppliers, continuous monitoring of vendor security',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-7', 'ctrl-8'],
      tags: ['supply-chain', 'vendor-risk', 'operational'],
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-12-10'),
    },
    {
      id: 'risk-4',
      organizationId: 'demo-org-id',
      title: 'Financial Fraud Risk',
      description: 'Risk of financial losses due to internal or external fraud activities',
      category: 'Financial',
      severity: 'HIGH' as RiskSeverity,
      likelihood: 'LOW',
      impact: 'HIGH',
      status: 'MITIGATED' as RiskStatus,
      riskScore: 45,
      owner: 'David Martinez',
      department: 'Finance',
      identifiedDate: new Date('2024-01-20'),
      lastReviewDate: new Date('2024-10-20'),
      nextReviewDate: new Date('2025-01-20'),
      mitigationStrategy: 'Segregation of duties, transaction monitoring, regular audits, fraud detection systems',
      residualRisk: 'LOW',
      controls: ['ctrl-9', 'ctrl-10', 'ctrl-11'],
      tags: ['financial', 'fraud', 'audit'],
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-10-20'),
    },
    {
      id: 'risk-5',
      organizationId: 'demo-org-id',
      title: 'Business Continuity Risk',
      description: 'Risk of business operations disruption due to natural disasters or system failures',
      category: 'Operational',
      severity: 'MEDIUM' as RiskSeverity,
      likelihood: 'LOW',
      impact: 'HIGH',
      status: 'ACTIVE' as RiskStatus,
      riskScore: 55,
      owner: 'Emily Wilson',
      department: 'Business Continuity',
      identifiedDate: new Date('2024-04-05'),
      lastReviewDate: new Date('2024-11-05'),
      nextReviewDate: new Date('2025-05-05'),
      mitigationStrategy: 'Disaster recovery plan, backup systems, regular DR testing, cloud redundancy',
      residualRisk: 'MEDIUM',
      controls: ['ctrl-12', 'ctrl-13'],
      tags: ['business-continuity', 'disaster-recovery', 'operational'],
      createdAt: new Date('2024-04-05'),
      updatedAt: new Date('2024-11-05'),
    },
  ],

  // Demo Controls
  controls: [
    {
      id: 'ctrl-1',
      organizationId: 'demo-org-id',
      name: 'Multi-Factor Authentication',
      description: 'Require MFA for all user accounts accessing sensitive systems',
      type: 'PREVENTIVE' as ControlType,
      category: 'Access Control',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 95,
      owner: 'IT Security Team',
      implementationDate: new Date('2024-02-01'),
      lastTestDate: new Date('2024-12-01'),
      nextTestDate: new Date('2025-01-01'),
      testFrequency: 'MONTHLY',
      automationLevel: 'FULLY_AUTOMATED',
      cost: 50000,
      relatedRisks: ['risk-1'],
      evidence: ['MFA implementation report', 'User enrollment statistics'],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'ctrl-2',
      organizationId: 'demo-org-id',
      name: 'Data Encryption',
      description: 'Encrypt all sensitive data at rest and in transit using AES-256',
      type: 'PREVENTIVE' as ControlType,
      category: 'Data Protection',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 90,
      owner: 'Data Security Team',
      implementationDate: new Date('2024-01-20'),
      lastTestDate: new Date('2024-11-15'),
      nextTestDate: new Date('2025-02-15'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'FULLY_AUTOMATED',
      cost: 75000,
      relatedRisks: ['risk-1'],
      evidence: ['Encryption audit report', 'Certificate management logs'],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-11-15'),
    },
    {
      id: 'ctrl-3',
      organizationId: 'demo-org-id',
      name: 'Security Monitoring',
      description: '24/7 SIEM monitoring with automated threat detection and response',
      type: 'DETECTIVE' as ControlType,
      category: 'Monitoring',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 85,
      owner: 'SOC Team',
      implementationDate: new Date('2024-03-01'),
      lastTestDate: new Date('2024-12-05'),
      nextTestDate: new Date('2025-01-05'),
      testFrequency: 'MONTHLY',
      automationLevel: 'PARTIALLY_AUTOMATED',
      cost: 120000,
      relatedRisks: ['risk-1'],
      evidence: ['SIEM dashboard screenshots', 'Incident response metrics'],
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-12-05'),
    },
    {
      id: 'ctrl-4',
      organizationId: 'demo-org-id',
      name: 'Compliance Training',
      description: 'Mandatory annual compliance training for all employees',
      type: 'PREVENTIVE' as ControlType,
      category: 'Training',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 80,
      owner: 'HR Department',
      implementationDate: new Date('2024-01-01'),
      lastTestDate: new Date('2024-10-01'),
      nextTestDate: new Date('2025-01-01'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'PARTIALLY_AUTOMATED',
      cost: 30000,
      relatedRisks: ['risk-2'],
      evidence: ['Training completion reports', 'Assessment scores'],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-10-01'),
    },
    {
      id: 'ctrl-5',
      organizationId: 'demo-org-id',
      name: 'Data Privacy Impact Assessments',
      description: 'Conduct DPIA for all new data processing activities',
      type: 'PREVENTIVE' as ControlType,
      category: 'Privacy',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 88,
      owner: 'Privacy Team',
      implementationDate: new Date('2024-02-15'),
      lastTestDate: new Date('2024-11-01'),
      nextTestDate: new Date('2025-02-01'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'MANUAL',
      cost: 40000,
      relatedRisks: ['risk-2'],
      evidence: ['DPIA reports', 'Risk assessment documentation'],
      createdAt: new Date('2024-02-15'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'ctrl-6',
      organizationId: 'demo-org-id',
      name: 'Automated Compliance Monitoring',
      description: 'Continuous monitoring of compliance requirements using automated tools',
      type: 'DETECTIVE' as ControlType,
      category: 'Compliance',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 92,
      owner: 'Compliance Team',
      implementationDate: new Date('2024-04-01'),
      lastTestDate: new Date('2024-12-01'),
      nextTestDate: new Date('2025-01-01'),
      testFrequency: 'MONTHLY',
      automationLevel: 'FULLY_AUTOMATED',
      cost: 80000,
      relatedRisks: ['risk-2'],
      evidence: ['Compliance dashboard reports', 'Automated scan results'],
      createdAt: new Date('2024-04-01'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'ctrl-7',
      organizationId: 'demo-org-id',
      name: 'Vendor Risk Assessment',
      description: 'Comprehensive security assessment of all critical vendors',
      type: 'PREVENTIVE' as ControlType,
      category: 'Third Party Risk',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 75,
      owner: 'Procurement Team',
      implementationDate: new Date('2024-03-15'),
      lastTestDate: new Date('2024-09-15'),
      nextTestDate: new Date('2025-03-15'),
      testFrequency: 'SEMI_ANNUAL',
      automationLevel: 'PARTIALLY_AUTOMATED',
      cost: 45000,
      relatedRisks: ['risk-3'],
      evidence: ['Vendor assessment reports', 'Risk scoring matrices'],
      createdAt: new Date('2024-03-15'),
      updatedAt: new Date('2024-09-15'),
    },
    {
      id: 'ctrl-8',
      organizationId: 'demo-org-id',
      name: 'Supply Chain Monitoring',
      description: 'Continuous monitoring of supply chain vendors for security incidents',
      type: 'DETECTIVE' as ControlType,
      category: 'Third Party Risk',
      status: 'IN_PROGRESS' as ControlStatus,
      effectiveness: 70,
      owner: 'Supply Chain Team',
      implementationDate: new Date('2024-05-01'),
      lastTestDate: new Date('2024-11-01'),
      nextTestDate: new Date('2025-02-01'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'PARTIALLY_AUTOMATED',
      cost: 60000,
      relatedRisks: ['risk-3'],
      evidence: ['Monitoring reports', 'Incident alerts'],
      createdAt: new Date('2024-05-01'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'ctrl-9',
      organizationId: 'demo-org-id',
      name: 'Segregation of Duties',
      description: 'Enforce separation of duties for all financial transactions',
      type: 'PREVENTIVE' as ControlType,
      category: 'Financial Controls',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 90,
      owner: 'Finance Team',
      implementationDate: new Date('2024-01-10'),
      lastTestDate: new Date('2024-10-10'),
      nextTestDate: new Date('2025-01-10'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'FULLY_AUTOMATED',
      cost: 25000,
      relatedRisks: ['risk-4'],
      evidence: ['Access control matrix', 'Audit logs'],
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-10-10'),
    },
    {
      id: 'ctrl-10',
      organizationId: 'demo-org-id',
      name: 'Transaction Monitoring',
      description: 'Real-time monitoring of financial transactions for anomalies',
      type: 'DETECTIVE' as ControlType,
      category: 'Financial Controls',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 88,
      owner: 'Finance Team',
      implementationDate: new Date('2024-02-20'),
      lastTestDate: new Date('2024-11-20'),
      nextTestDate: new Date('2025-02-20'),
      testFrequency: 'MONTHLY',
      automationLevel: 'FULLY_AUTOMATED',
      cost: 90000,
      relatedRisks: ['risk-4'],
      evidence: ['Transaction monitoring reports', 'Alert investigation logs'],
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-11-20'),
    },
    {
      id: 'ctrl-11',
      organizationId: 'demo-org-id',
      name: 'Internal Audit Program',
      description: 'Regular internal audits of financial processes and controls',
      type: 'DETECTIVE' as ControlType,
      category: 'Audit',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 85,
      owner: 'Internal Audit',
      implementationDate: new Date('2024-01-01'),
      lastTestDate: new Date('2024-09-01'),
      nextTestDate: new Date('2025-03-01'),
      testFrequency: 'QUARTERLY',
      automationLevel: 'MANUAL',
      cost: 100000,
      relatedRisks: ['risk-4'],
      evidence: ['Audit reports', 'Finding remediation tracking'],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-09-01'),
    },
    {
      id: 'ctrl-12',
      organizationId: 'demo-org-id',
      name: 'Disaster Recovery Plan',
      description: 'Comprehensive DR plan with RTO/RPO targets and regular testing',
      type: 'CORRECTIVE' as ControlType,
      category: 'Business Continuity',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 82,
      owner: 'IT Operations',
      implementationDate: new Date('2024-04-15'),
      lastTestDate: new Date('2024-10-15'),
      nextTestDate: new Date('2025-04-15'),
      testFrequency: 'SEMI_ANNUAL',
      automationLevel: 'PARTIALLY_AUTOMATED',
      cost: 150000,
      relatedRisks: ['risk-5'],
      evidence: ['DR test results', 'Recovery time metrics'],
      createdAt: new Date('2024-04-15'),
      updatedAt: new Date('2024-10-15'),
    },
    {
      id: 'ctrl-13',
      organizationId: 'demo-org-id',
      name: 'Data Backup and Recovery',
      description: 'Automated daily backups with offsite storage and regular recovery testing',
      type: 'CORRECTIVE' as ControlType,
      category: 'Data Protection',
      status: 'IMPLEMENTED' as ControlStatus,
      effectiveness: 95,
      owner: 'IT Operations',
      implementationDate: new Date('2024-01-05'),
      lastTestDate: new Date('2024-12-05'),
      nextTestDate: new Date('2025-01-05'),
      testFrequency: 'MONTHLY',
      automationLevel: 'FULLY_AUTOMATED',
      cost: 70000,
      relatedRisks: ['risk-5'],
      evidence: ['Backup success logs', 'Recovery test documentation'],
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-12-05'),
    },
  ],

  // Demo Vendor Assessments
  vendorAssessments: [
    {
      id: 'vendor-1',
      organizationId: 'demo-org-id',
      vendorName: 'CloudTech Solutions',
      vendorType: 'Cloud Infrastructure Provider',
      criticality: 'CRITICAL',
      assessmentDate: new Date('2024-11-01'),
      nextAssessmentDate: new Date('2025-05-01'),
      overallRiskScore: 25,
      securityScore: 90,
      complianceScore: 88,
      financialScore: 92,
      operationalScore: 85,
      status: 'APPROVED',
      findings: [
        'Strong security controls in place',
        'SOC 2 Type II certified',
        'Minor improvement needed in incident response procedures',
      ],
      recommendations: [
        'Review incident response SLA',
        'Request quarterly security reports',
      ],
      contractValue: 500000,
      contractExpiry: new Date('2025-12-31'),
      primaryContact: 'vendor.contact@cloudtech.com',
      certifications: ['SOC 2', 'ISO 27001', 'PCI DSS'],
      createdAt: new Date('2024-11-01'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'vendor-2',
      organizationId: 'demo-org-id',
      vendorName: 'SecurePayments Inc',
      vendorType: 'Payment Processor',
      criticality: 'CRITICAL',
      assessmentDate: new Date('2024-10-15'),
      nextAssessmentDate: new Date('2025-04-15'),
      overallRiskScore: 30,
      securityScore: 85,
      complianceScore: 95,
      financialScore: 88,
      operationalScore: 82,
      status: 'APPROVED',
      findings: [
        'PCI DSS Level 1 compliant',
        'Robust fraud detection mechanisms',
        'Need for enhanced API security documentation',
      ],
      recommendations: [
        'Implement API rate limiting',
        'Enhance monitoring of transaction anomalies',
      ],
      contractValue: 250000,
      contractExpiry: new Date('2025-10-31'),
      primaryContact: 'security@securepayments.com',
      certifications: ['PCI DSS Level 1', 'SOC 1', 'ISO 27001'],
      createdAt: new Date('2024-10-15'),
      updatedAt: new Date('2024-10-15'),
    },
    {
      id: 'vendor-3',
      organizationId: 'demo-org-id',
      vendorName: 'DataAnalytics Pro',
      vendorType: 'Analytics Platform',
      criticality: 'HIGH',
      assessmentDate: new Date('2024-09-20'),
      nextAssessmentDate: new Date('2025-03-20'),
      overallRiskScore: 40,
      securityScore: 78,
      complianceScore: 82,
      financialScore: 90,
      operationalScore: 88,
      status: 'CONDITIONAL',
      findings: [
        'Data encryption needs improvement',
        'Access controls are adequate',
        'Missing GDPR compliance documentation',
      ],
      recommendations: [
        'Implement end-to-end encryption',
        'Complete GDPR compliance audit',
        'Enhance user access logging',
      ],
      contractValue: 150000,
      contractExpiry: new Date('2025-09-30'),
      primaryContact: 'support@dataanalytics.com',
      certifications: ['SOC 2 Type I'],
      createdAt: new Date('2024-09-20'),
      updatedAt: new Date('2024-09-20'),
    },
    {
      id: 'vendor-4',
      organizationId: 'demo-org-id',
      vendorName: 'HR Management Systems',
      vendorType: 'HR Software',
      criticality: 'MEDIUM',
      assessmentDate: new Date('2024-08-10'),
      nextAssessmentDate: new Date('2025-08-10'),
      overallRiskScore: 35,
      securityScore: 80,
      complianceScore: 85,
      financialScore: 82,
      operationalScore: 79,
      status: 'APPROVED',
      findings: [
        'Good data protection practices',
        'Regular security updates',
        'Need for better disaster recovery documentation',
      ],
      recommendations: [
        'Document DR procedures',
        'Implement MFA for all admin accounts',
      ],
      contractValue: 75000,
      contractExpiry: new Date('2025-08-31'),
      primaryContact: 'security@hrsystems.com',
      certifications: ['ISO 27001', 'GDPR Compliant'],
      createdAt: new Date('2024-08-10'),
      updatedAt: new Date('2024-08-10'),
    },
    {
      id: 'vendor-5',
      organizationId: 'demo-org-id',
      vendorName: 'Marketing Automation Co',
      vendorType: 'Marketing Software',
      criticality: 'LOW',
      assessmentDate: new Date('2024-07-05'),
      nextAssessmentDate: new Date('2025-07-05'),
      overallRiskScore: 45,
      securityScore: 75,
      complianceScore: 78,
      financialScore: 85,
      operationalScore: 80,
      status: 'UNDER_REVIEW',
      findings: [
        'Basic security controls in place',
        'Limited compliance certifications',
        'Adequate data handling procedures',
      ],
      recommendations: [
        'Obtain SOC 2 certification',
        'Enhance API security',
        'Implement data retention policies',
      ],
      contractValue: 50000,
      contractExpiry: new Date('2025-07-31'),
      primaryContact: 'info@marketingauto.com',
      certifications: ['GDPR Compliant'],
      createdAt: new Date('2024-07-05'),
      updatedAt: new Date('2024-07-05'),
    },
  ],

  // Demo Compliance Items
  compliance: [
    {
      id: 'comp-1',
      organizationId: 'demo-org-id',
      framework: 'GDPR',
      requirement: 'Data Protection Officer Appointment',
      description: 'Appoint a Data Protection Officer to oversee GDPR compliance',
      status: 'COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-01-01'),
      lastAssessmentDate: new Date('2024-11-01'),
      evidence: ['DPO appointment letter', 'DPO responsibilities document'],
      responsibleParty: 'Legal Department',
      notes: 'DPO appointed and actively monitoring compliance',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-11-01'),
    },
    {
      id: 'comp-2',
      organizationId: 'demo-org-id',
      framework: 'SOC 2',
      requirement: 'Access Control Review',
      description: 'Quarterly review of user access rights and privileges',
      status: 'COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-03-31'),
      lastAssessmentDate: new Date('2024-12-01'),
      evidence: ['Access review reports', 'Approval documentation'],
      responsibleParty: 'IT Security',
      notes: 'Q4 2024 review completed successfully',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'comp-3',
      organizationId: 'demo-org-id',
      framework: 'PCI DSS',
      requirement: 'Network Segmentation',
      description: 'Maintain network segmentation between cardholder data environment and other networks',
      status: 'PARTIALLY_COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-02-28'),
      lastAssessmentDate: new Date('2024-10-15'),
      evidence: ['Network diagram', 'Segmentation test results'],
      responsibleParty: 'Network Team',
      notes: 'Additional segmentation required for new payment processing system',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-10-15'),
    },
    {
      id: 'comp-4',
      organizationId: 'demo-org-id',
      framework: 'ISO 27001',
      requirement: 'Risk Assessment',
      description: 'Annual information security risk assessment',
      status: 'COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-06-30'),
      lastAssessmentDate: new Date('2024-06-30'),
      evidence: ['Risk assessment report', 'Risk treatment plan'],
      responsibleParty: 'Risk Management',
      notes: '2024 assessment completed with all high risks addressed',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-06-30'),
    },
    {
      id: 'comp-5',
      organizationId: 'demo-org-id',
      framework: 'HIPAA',
      requirement: 'Business Associate Agreements',
      description: 'Maintain current BAAs with all vendors handling PHI',
      status: 'NON_COMPLIANT' as ComplianceStatus,
      dueDate: new Date('2025-01-31'),
      lastAssessmentDate: new Date('2024-11-15'),
      evidence: ['BAA inventory', 'Signed agreements'],
      responsibleParty: 'Legal Department',
      notes: '3 vendor BAAs pending renewal',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-11-15'),
    },
  ],

  // Demo Test Results
  testResults: [
    {
      id: 'test-1',
      controlId: 'ctrl-1',
      testDate: new Date('2024-12-01'),
      testType: 'Automated',
      result: 'PASS',
      findings: 'MFA enforcement working correctly across all systems',
      evidence: ['Test execution logs', 'Screenshot evidence'],
      tester: 'Security Team',
      nextTestDate: new Date('2025-01-01'),
    },
    {
      id: 'test-2',
      controlId: 'ctrl-2',
      testDate: new Date('2024-11-15'),
      testType: 'Manual',
      result: 'PASS',
      findings: 'All sensitive data properly encrypted',
      evidence: ['Encryption scan results', 'Configuration review'],
      tester: 'Security Team',
      nextTestDate: new Date('2025-02-15'),
    },
    {
      id: 'test-3',
      controlId: 'ctrl-7',
      testDate: new Date('2024-09-15'),
      testType: 'Manual',
      result: 'FAIL',
      findings: '2 vendors missing security documentation',
      evidence: ['Assessment checklist', 'Vendor communication'],
      tester: 'Procurement Team',
      nextTestDate: new Date('2025-03-15'),
    },
  ],

  // Demo Incidents
  incidents: [
    {
      id: 'inc-1',
      organizationId: 'demo-org-id',
      title: 'Phishing Email Campaign Detected',
      description: 'Multiple employees received sophisticated phishing emails',
      severity: 'MEDIUM',
      status: 'RESOLVED',
      detectedDate: new Date('2024-11-20'),
      resolvedDate: new Date('2024-11-21'),
      impactedSystems: ['Email System', 'User Accounts'],
      rootCause: 'Social engineering attack',
      remediation: 'User training conducted, email filters updated',
      lessonsLearned: 'Need for enhanced email security and regular phishing simulations',
      createdAt: new Date('2024-11-20'),
      updatedAt: new Date('2024-11-21'),
    },
    {
      id: 'inc-2',
      organizationId: 'demo-org-id',
      title: 'Database Performance Degradation',
      description: 'Production database experiencing slow query performance',
      severity: 'HIGH',
      status: 'IN_PROGRESS',
      detectedDate: new Date('2024-12-10'),
      resolvedDate: null,
      impactedSystems: ['Production Database', 'Web Application'],
      rootCause: 'Under investigation',
      remediation: 'Query optimization in progress',
      lessonsLearned: '',
      createdAt: new Date('2024-12-10'),
      updatedAt: new Date('2024-12-10'),
    },
  ],

  // Demo Audit Logs
  auditLogs: [
    {
      id: 'audit-1',
      timestamp: new Date('2024-12-12T10:30:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'LOGIN',
      resource: 'Authentication System',
      details: 'Successful login from IP 192.168.1.100',
      result: 'SUCCESS',
    },
    {
      id: 'audit-2',
      timestamp: new Date('2024-12-12T10:35:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'VIEW',
      resource: 'Risk Dashboard',
      details: 'Accessed risk dashboard',
      result: 'SUCCESS',
    },
    {
      id: 'audit-3',
      timestamp: new Date('2024-12-12T10:40:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'UPDATE',
      resource: 'Risk Assessment',
      details: 'Updated risk score for Risk ID: risk-1',
      result: 'SUCCESS',
    },
    {
      id: 'audit-4',
      timestamp: new Date('2024-12-12T10:45:00'),
      userId: 'demo-admin-id',
      userName: 'Demo Admin',
      action: 'CREATE',
      resource: 'Control Test',
      details: 'Initiated control test for Control ID: ctrl-1',
      result: 'SUCCESS',
    },
  ],

  // Demo Dashboard Metrics
  metrics: {
    totalRisks: 5,
    highRisks: 3,
    mediumRisks: 2,
    lowRisks: 0,
    activeControls: 12,
    failedControls: 1,
    vendorsAssessed: 5,
    vendorsApproved: 3,
    complianceScore: 85,
    overallRiskScore: 62,
    openIncidents: 1,
    resolvedIncidents: 1,
    upcomingAssessments: 3,
    overdueItems: 1,
  },
};

// Helper function to get demo data for a specific entity
export function getDemoData(entity: string, organizationId: string) {
  if (organizationId !== 'demo-org-id') {
    return null;
  }

  switch (entity) {
    case 'risks':
      return demoData.risks;
    case 'controls':
      return demoData.controls;
    case 'vendors':
      return demoData.vendorAssessments;
    case 'compliance':
      return demoData.compliance;
    case 'tests':
      return demoData.testResults;
    case 'incidents':
      return demoData.incidents;
    case 'audit':
      return demoData.auditLogs;
    case 'metrics':
      return demoData.metrics;
    case 'organization':
      return demoData.organization;
    default:
      return null;
  }
}

// Helper to check if a user is using demo mode
export function isDemoUser(userId: string): boolean {
  return userId === 'demo-admin-id';
}

// Helper to get demo user details
export function getDemoUser() {
  return {
    id: 'demo-admin-id',
    email: 'admin@riscura.com',
    firstName: 'Demo',
    lastName: 'Admin',
    role: 'ADMIN',
    permissions: ['*'],
    organizationId: 'demo-org-id',
    organization: demoData.organization,
  };
}